# Challenge 1 - T-test

In statistics, t-test is used to test if two data samples have a significant difference between their means. There are two types of t-test:

* **Student's t-test** (a.k.a. independent or uncorrelated t-test). This type of t-test is to compare the samples of **two independent populations** (e.g. test scores of students in two different classes). `scipy` provides the [`ttest_ind`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_ind.html) method to conduct student's t-test.

* **Paired t-test** (a.k.a. dependent or correlated t-test). This type of t-test is to compare the samples of **the same population** (e.g. scores of different tests of students in the same class). `scipy` provides the [`ttest_re`](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.ttest_rel.html) method to conduct paired t-test.

Both types of t-tests return a number which is called the **p-value**. If p-value is below 0.05, we can confidently declare the null-hypothesis is rejected and the difference is significant. If p-value is between 0.05 and 0.1, we may also declare the null-hypothesis is rejected but we are not highly confident. If p-value is above 0.1 we do not reject the null-hypothesis.

Read more about the t-test in [this article](http://b.link/test50) and [this Quora](http://b.link/unpaired97). Make sure you understand when to use which type of t-test.

In [2]:
# Import libraries
import pandas as pd
import scipy.stats as st
import numpy as np

#### Import dataset

In this challenge we will work on the Pokemon dataset. The goal is to test whether different groups of pokemon (e.g. Legendary vs Normal, Generation 1 vs 2, single-type vs dual-type) have different stats (e.g. HP, Attack, Defense, etc.).

In [3]:
pokemon = pd.read_csv('pokemon.csv')
pokemon.head(30)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
24,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
25,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False
26,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False
27,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False

#### First we want to define a function with which we can test the means of a feature set of two samples. 

In the next cell you'll see the annotations of the Python function that explains what this function does and its arguments and returned value. This type of annotation is called **docstring** which is a convention used among Python developers. The docstring convention allows developers to write consistent tech documentations for their codes so that others can read. It also allows some websites to automatically parse the docstrings and display user-friendly documentations.

Follow the specifications of the docstring and complete the function.

In [12]:
def t_test_features(s1, s2, features=['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Total']):
    """Test means of a feature set of two samples
    
    Args:
        s1 (dataframe): sample 1
        s2 (dataframe): sample 2
        features (list): an array of features to test
    
    Returns:
        dict: a dictionary of t-test scores for each feature where the feature name is the key and the p-value is the value
    """
    results = {}

    for feature in features:
        results[feature] = st.ttest_1samp(s2[feature], s1[feature].mean(), nan_policy = 'omit')[1]
    
    return results

#### Using the `t_test_features` function, conduct t-test for Lengendary vs non-Legendary pokemons.

*Hint: your output should look like below:*

```
{'HP': 1.0026911708035284e-13,
 'Attack': 2.520372449236646e-16,
 'Defense': 4.8269984949193316e-11,
 'Sp. Atk': 1.5514614112239812e-21,
 'Sp. Def': 2.2949327864052826e-15,
 'Speed': 1.049016311882451e-18,
 'Total': 9.357954335957446e-47}
 ```

In [17]:
legendary_pokemons = pokemon[pokemon['Legendary'] == True]
non_legendary_pokemons = pokemon[pokemon['Legendary'] == False]

In [16]:
t_test_results = t_test_features(legendary_pokemon, non_legendary_pokemon)
t_test_results

{'HP': 1.668331877441655e-117,
 'Attack': 6.501299300067182e-167,
 'Defense': 1.3561763931654067e-100,
 'Sp. Atk': 6.409794860195272e-239,
 'Sp. Def': 9.179029282985046e-182,
 'Speed': 7.642385669570052e-152,
 'Total': 8.87320546429684e-267}

#### From the test results above, what conclusion can you make? Do Legendary and non-Legendary pokemons have significantly different stats on each feature?

In [ ]:
# From the result above we can se that there is a significant difference between Legendary and Non-legendary pokemons. P-valur here is close to zero.

#### Next, conduct t-test for Generation 1 and Generation 2 pokemons.

In [22]:
generation1 = pokemon[pokemon['Generation'] == 1]
generration2 = pokemon[pokemon['Generation'] == 2]

In [24]:
t_test_results2 = t_test_features(generation1, generration2)
t_test_results2

{'HP': 0.07260185952473824,
 'Attack': 0.14971681662441522,
 'Defense': 0.5089775796337688,
 'Sp. Atk': 0.03187875902114549,
 'Sp. Def': 0.1189248010611017,
 'Speed': 9.184945831398406e-05,
 'Total': 0.46630243531930904}

#### What conclusions can you make?

In [ ]:
# Looking at those p-values we got we can see that there is significant difference for Sp. attack (0,03<0,05) and also for Speet (close to zero)

#### Compare pokemons who have single type vs those having two types.

In [26]:
one_type = pokemon[pokemon['Type 2'].isnull()]
two_types = pokemon.dropna(subset=['Type 2'], axis = 0)

In [29]:
t_test_features(one_type, two_types)

{'HP': 0.010764022997835195,
 'Attack': 2.8168493832232366e-07,
 'Defense': 2.856983483500764e-13,
 'Sp. Atk': 2.151710925487231e-07,
 'Sp. Def': 5.806576124932923e-08,
 'Speed': 0.0010238231076733799,
 'Total': 3.6549525209101034e-13}

#### What conclusions can you make?

In [ ]:
# Here we can say that those features all are close to 0. We can also say they are signigicantly different to for one type and dual types.

#### Now, we want to compare whether there are significant differences of `Attack` vs `Defense`  and  `Sp. Atk` vs `Sp. Def` of all pokemons. Please write your code below.

*Hint: are you comparing different populations or the same population?*

In [ ]:
# we will be looking at all pokemons together

In [ ]:
# H0 = attack is equal to the population mean of defense
# Halt = attack is not equal to the population mean of defense
# H0 = Sp. attack is equal to the population mean Sp. Def
# Halt = Sp. attack is not equal to the population mean Sp. Def

In [33]:
st.ttest_1samp(pokemon['Attack'], pokemon['Defense'].mean(), nan_policy = 'omit')

TtestResult(statistic=4.4954813919438585, pvalue=7.967950832362132e-06, df=799)

In [35]:
st.ttest_1samp(pokemon['Sp. Atk'], pokemon['Sp. Def'].mean(), nan_policy = 'omit')

TtestResult(statistic=0.7930623304000574, pvalue=0.42797693754422494, df=799)

#### What conclusions can you make?

In [ ]:
# in first hypotesis we can sau that attack is different from the population mean of Defense. We need to reject hypotesis 0.
# in the second pare sp. attack and sp.def we cannot reject hypotesis 0 because pvalue is bigger then 0.05